/*
16) Realize uma consulta que retorne quais livros foram emprestados para a
cliente Josimeiri Calgaro Juvenal.
*/

SELECT
    LIV_TITULO
FROM
         TB_CLIENTE
    JOIN TB_EMPRESTIMO ON CLI_CODIGO = EMP_CODCLIENTE
    JOIN TB_EXEMPLAREMPRESTIMO ON EMP_CODIGO = EXEPRE_CODEMPRESTIMO
    JOIN TB_EXEMPLAR ON EXEPRE_CODEXEMPLAR = EXE_CODIGO
    JOIN TB_LIVRO ON EXE_CODLIVRO = LIV_CODIGO
WHERE
    UPPER(CLI_NOME) = 'JOSIMEIRI CALGARO JUVENAL';