/*
12) Realize uma consulta que retorne todos os livros emprestados por Carlos
pereira.
*/

SELECT
    EXEPRE_CODEMPRESTIMO
FROM
    TB_EXEMPLAREMPRESTIMO
JOIN
    TB_EMPRESTIMO ON EXEPRE_CODEMPRESTIMO = EMP_CODIGO
JOIN
    TB_FUNCIONARIO ON EMP_CODFUNCIONARIO = FUN_CODIGO
WHERE
    UPPER(FUN_NOME) = 'CARLOS PEREIRA';