/*
13) Realize uma consulta que retorne a quantidade de reservas por mês
realizadas pelo funcionário Carlos Pereira.
*/

SELECT
    FUN_NOME,
    COUNT(RES_CODIGO) AS QUANTIDADE,
    TO_CHAR(RES_DATA, 'YYYY-MM') AS MES
FROM
         TB_FUNCIONARIO
    JOIN TB_EMPRESTIMO ON EMP_CODFUNCIONARIO = FUN_CODIGO
    JOIN TB_EXEMPLAREMPRESTIMO ON EXEPRE_CODEMPRESTIMO = EMP_CODIGO
    JOIN TB_RESERVA ON RES_CODIGO = EXEPRE_CODRESERVA
WHERE
    UPPER(FUN_NOME) = 'CARLOS PEREIRA'
GROUP BY
    FUN_NOME,
    TO_CHAR(RES_DATA, 'YYYY-MM');