/*
16) Realize uma consulta que retorne todos os exemplares que geraram mais R$
3,00 de multa no ano de 2008.
*/

SELECT
    EXEPRE_CODEXEMPLAR AS EXEMPLAR,
    TO_CHAR(EXEPRE_DTPREVDEV, 'YYYY') AS ANO,
    SUM(EXEPRE_VALORMULTA) AS MULTA
FROM
    TB_EXEMPLAREMPRESTIMO
WHERE
    TO_CHAR(EXEPRE_DTPREVDEV, 'YYYY') = '2008'
GROUP BY
    EXEPRE_CODEXEMPLAR,
    TO_CHAR(EXEPRE_DTPREVDEV, 'YYYY')
HAVING
    SUM(EXEPRE_VALORMULTA) > 3;