/*
c) Apresente o endereço completo de todos os prédios da cidade de Cascavel
e que possuem "mobilia" da marca "MARCA_TAL".
*/

SELECT
    END_DESCRICAO,
    PRE_NUMERO,
    BAI_DESCRICAO,
    CID_DESCRICAO
FROM
         TB_PATRIMONIO
    JOIN TB_MARCA ON PAT_CODMARCA = MAR_CODIGO
    JOIN TB_ENDERECO ON PAT_CODDENDERECO = END_CODIGO
    JOIN TB_PREDIO ON PAT_CODPREDIO = PRE_CODIGO
    JOIN TB_BAIRRO ON PRE_CODBAIRRO = BAI_CODIGO
    JOIN TB_CIDADE ON BAI_CODCIDADE = CID_CODIGO
    JOIN TB_TIPO ON PAT_CODTIPO = TIP_CODIGO
WHERE
        UPPER(CID_NOME) = 'CASCAVEL'
    AND UPPER(TIP_DESCRICAO) = 'MOBILIA'
    AND UPPER(MAR_DESCRICAO) = 'MARCA_TAL';