/*
h) Apresente todos os patrimônios que foram adquiridos no ano de 2006
para o departamento de obras localizado na rua "BAHIA" da cidade
de LONDRINA e que sejam da marca "CHINGUILING".
*/

SELECT
    PAT_DESCRICAO
FROM
         TB_PATRIMONIO
    JOIN TB_DEPARTAMENTO ON PAT_CODDEPARTAMENTO = DEP_CODIGO
    JOIN TB_PREDIO ON PAT_CODPREDIO = PRE_CODIGO
    JOIN TB_ENDERECO ON PRE_CODENDERECO = END_CODIGO
    JOIN TB_CIDADE ON PRE_CODCIDADE = CID_CODIGO
    JOIN TB_MARCA ON PAT_CODMARCA = MAR_CODIGO
WHERE
       TO_CHAR(PAT_DATAAQUISICAO, 'YYYY') = '2006'
    AND UPPER(DEP_DESCRICAO) = 'OBRAS'
    AND UPPER(END_DESCRICAO) = 'RUA BAHIA'
    AND UPPER(CID_DESCRICAO) = 'LONDRINA'
    AND UPPER(MAR_DESCRICAO) = 'CHINGUILING';