/*
j) Apresente quantos patrimônios o departamento "OBRAS" possui na
cidade de CASCAVEL, mas que não estejam na "RUA DAS FLORES"
e nem sejam da marca "VALITA".
*/

SELECT
    COUNT(*) AS QUANTIDADE
FROM
         TB_PATRIMONIO
    JOIN TB_DEPARTAMENTO ON PAT_CODDEPARTAMENTO = DEP_CODIGO
    JOIN TB_PREDIO ON PAT_CODPREDIO = PRE_CODIGO
    JOIN TB_ENDERECO ON PRE_CODENDERECO = END_CODIGO
    JOIN TB_CIDADE ON PRE_CODCIDADE = CID_CODIGO
    JOIN TB_MARCA ON PAT_CODMARCA = MAR_CODIGO
WHERE
    UPPER(DEP_DESCRICAO) = 'OBRAS'
    AND UPPER(CID_DESCRICAO) = 'CASCAVEL'
    AND UPPER(END_DESCRICAO) != 'RUA DAS FLORES'
    AND UPPER(MAR_DESCRICAO) != 'VALITA';