/*
l) Apresente o valor total dos produtos dos prédios de londrina localizado
na "RUA DAS FLORES".
*/

SELECT
    PRE_DESCRICAO,
    SUM(PAT_VLRAQUISICAO) AS VALOR_TOTAL
FROM
         TB_PATRIMONIO
    JOIN TB_PREDIO ON PAT_CODPREDIO = PRE_CODIGO
    JOIN TB_CIDADE ON PRE_CODCIDADE = CID_CODIGO
    JOIN TB_ENDERECO ON PRE_CODENDERECO = END_CODIGO
WHERE
        UPPER(CID_DESCRICAO) = 'FOZ DO IGUAÇU'
    AND UPPER(END_DESCRICAO) = 'RUA ARGENTINA'
GROUP BY
    PRE_DESCRICAO;